sudo: required
addons:
  chrome: stable

language: node_js

node_js:
  - node # will use latest node

branches:
  only:
    - master

before_script: # commands to run before the build step
  - npm install -g --silent @angular/cli

script: # the build step
  - ng build --prod
  - ng test

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
